# 1. Define the database.
databases:
  - name: exodia-api-db
    plan: free

# 2. Define the web service using Docker.
services:
  - type: web
    name: exodia-api
    plan: free
    runtime: docker
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: GEMINI_API_KEY
        sync: false