services:
  # 1. This defines your Laravel Web Service
  - type: web
    name: exodia-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 8000
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: psql
          name: exodia-api-db
          property: host
      - key: DB_PORT
        fromService:
          type: psql
          name: exodia-api-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: psql
          name: exodia-api-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: psql
          name: exodia-api-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: exodia-api-db
          property: password

  # 2. This defines your PostgreSQL Database Service
  - type: psql
    name: exodia-api-db
    plan: free