# This is the FINAL render.yaml file
services:
  - type: web
    name: exodia-api
    plan: free
    runtime: docker # It will use your Dockerfile
    
    envVars:
      - key: APP_KEY
        value: "base64:o/sim2JB/rkz2kwQKWKqzbJBHaxoYKTcNeWir7LLQi8=" # <-- PASTE YOUR KEY
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://exodia-api.onrender.com

      - key: LOG_CHANNEL
        value: stderr

      # --- TiDB Serverless (MySQL) Credentials ---
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
      - key: DB_DATABASE
        value: "test"
      - key: DB_USERNAME
        value: "Wunf2o5PGtikoB.root"
      - key: DB_PASSWORD
        value: "xqgRxZ5iwmDe6ote"
      - key: DB_PORT
        value: 4000
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
